version: '3.7'

services:
  #########################################################################
  #                               DB                                      #
  #########################################################################
  mongodb:
    image: mongo:latest ## mongodb version to use
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: documentorganizeradmin
      MONGO_INITDB_ROOT_PASSWORD: documentorganizeradmin
    volumes:
      - ./nosql-data:/data/db
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017 ## port for the mongodbserver
    networks:
      - document-net

  mysqldb:
    image: mysql
    # platform: linux/x86_64
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=documentorganizeradmin
      - MYSQL_PASSWORD=documentorganizeradmin
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
    volumes:
      - ./sql-data:/var/lib/mysql
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - document-net

  #########################################################################
  #                               Web API                                 #
  #########################################################################

  authentication_app:
    build: 
      context: ./authentication
      dockerfile: Dockerfile
    command: bash -c "python3 ./authentication/manage.py makemigrations && python3 ./authentication/manage.py migrate && python3 ./authentication/manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    restart: unless-stopped
    depends_on:
      - mysqldb
    networks:
      - document-net
  



  #########################################################################
  #                               NetWorks                                #
  #########################################################################

networks:
  document-net: