version: '3.7'

services:
  #########################################################################
  #                               DB                                      #
  #########################################################################
  mongodb:
    image: mongo ## mongodb version to use
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: documentorganizeradmin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./nosql-data:/data/db
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017 ## port for the mongodbserver
    networks:
      - document-net

  mysqldb:
    image: mysql
    # platform: linux/x86_64
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=documentorganizeradmin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - ./sql-data:/var/lib/mysql
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - document-net

  #########################################################################
  #                               Web API                                 #
  #########################################################################

  authentication:
    build: 
      context: ./authentication
      dockerfile: Dockerfile
    command: bash -c "python3 ./authentication/manage.py makemigrations Users && python3 ./authentication/manage.py migrate && python3 ./authentication/manage.py runserver 0.0.0.0:7001"
    volumes:
      - .:/app
    ports:
      - "7001:7001"
    restart: unless-stopped
    depends_on:
      - mysqldb
    networks:
      - document-net
  
  filemanagement:
    build: 
      context: ./file_management
      dockerfile: Dockerfile
    command: bash -c "python3 ./file_management/manage.py makemigrations && python3 ./file_management/manage.py migrate && python3 ./file_management/manage.py runserver 0.0.0.0:7002"
    volumes:
      - .:/app
    ports:
      - "7002:7002"
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - document-net

  fileuploader:
    build: 
      context: ./file_uploader
      dockerfile: Dockerfile
    command: bash -c "python3 ./file_uploader/manage.py makemigrations uploader && python3 ./file_uploader/manage.py migrate && python3 ./file_uploader/manage.py runserver 0.0.0.0:7003"
    volumes:
      - .:/app
    ports:
      - "7003:7003"
    restart: unless-stopped
    depends_on:
      - mysqldb
    networks:
      - document-net

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./web
        target: /app
      - type: bind
        source: ./web/node_modules
        target: /app/node_modules
    restart: unless-stopped
    depends_on:
      - fileuploader
      - filemanagement
      - authentication
    networks:
      - document-net

  nginx:
    depends_on:
      - mongodb
    image: nginx:alpine
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - document-net




  #########################################################################
  #                               NetWorks                                #
  #########################################################################

networks:
  document-net:
    driver: bridge


  